-- AlterTable
ALTER TABLE "PlayerSnapshot" ALTER COLUMN "combatLevel" SET DATA TYPE BIGINT,
ALTER COLUMN "totalSkill" SET DATA TYPE BIGINT,
ALTER COLUMN "totalXp" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "SkillSnapshot" ALTER COLUMN "rank" SET DATA TYPE BIGINT,
ALTER COLUMN "level" SET DATA TYPE BIGINT;
