export const Drops = [
  "Saradomin's Murmur",
  "Saradomin's Whisper",
  'Saradomin Hilt',
  'Saradomin Sword',
  'Off-Hand Armadyl Crossbow',
  "Saradomin's Hiss",
  'Armadyl crossbow',
  'Spectral sigil',
  'Bandos gloves',
  'Bandos chestplate',
  'Bandos boots',
  'Bandos helmet',
  'Bandos hilt',
  'Bandos tassets',
  'Armadyl gloves',
  'Armadyl chainskirt',
  'Armadyl Buckler',
  'Armadyl boots',
  'Armadyl Helmet',
  'Armadyl Hilt',
  'Armadyl Chestplate',
  'Zamorakian Spear',
  'Gown of Subjugation',
  'Hood of Subjugation',
  'Gloves of Subjugation',
  'Garb of Subjugation',
  'Ward of Subjugation',
  'Zamorak Hilt',
  'Divine Sigil',
  'Arcane Sigil',
  'Elysian Sigil',
  'Virtus boots',
  'Virtus Wand',
  'Virtus Book',
  'Virtus Mask',
  'Virtus Robe Top',
  'Virtus Robe Legs',
  'Virtus gloves',
  'Torva full helm',
  'Torva platebody',
  'Torva Platelegs',
  'Torva boots',
  'Torva gloves',
  'Pernix Cowl',
  'Pernix Body',
  'Pernix Chaps',
  'Pernix boots',
  'Pernix gloves',
  'Zaryte bow',
  'Crest of Zamorak',
  'Crest of Zaros',
  'Crest of Seren',
  'Crest of Sliske',
  'Blade of Nymora',
  'Blade of Avaryss',
  'Wand of the Cywir Elders',
  'Orb of the Cywir Elders',
  'Dragonrider Lance',
  'Shadow Glaive',
  'Off-Hand Shadow Glaive',
  'Spider Leg Top',
  'Spider Leg Middle',
  'Spider Leg Bottom',
  'Heart of the Archer',
  'Heart of the Seer',
  'Heart of the Beserker',
  'Heart of the Warrior',
  'Savage Spear Plume',
  'Savage Spear Tip',
  'Savage Spear Cap',
  'Savage Spear Shaft',
  'Omni Guard',
  'Soulbound Lantern',
  'Crown of the First Necromancer',
  'Robe top of the First Necromancer',
  'Robe bottom of the First Necromancer',
  'Hand wraps of the First Necromancer',
  'Foot wraps of the First Necromancer',
  'spider Fang',
  'spider Eye',
  'Scripture of Wen',
  'Greater Concentrated Blast Ability Codex',
  "Kerapac's Wristwraps",
  'Scipture of Jas',
  'Mazcab Ability Codex',
  'Achto Primeval Mask',
  'Achto Primeval Robe Top',
  'Achto Primeval Robe Legs',
  'Achto Primeval gloves',
  'Achto Primeval boots',
  'Achto Tempest Cowl',
  'Achto Tempest Body',
  'Achto Tempest Chaps',
  'Achto Tempest gloves',
  'Achto Tempest boots',
  'Achto Teralith Helmet',
  'Achto Teralith Cuirass',
  'Achto Teralith Leggings',
  'Achto Teralith Gauntlets',
  'Achto Teralith boots',
  'Greater Flurry Ability Codex',
  'Greater Fury Ability Codex',
  'Greater Barge Ability Codex',
  'Drygore Rapier',
  'Off-Hand Drygore Rapier',
  'Drygore Longsword',
  'Off-Hand Drygore Longsword',
  'Drygore Mace',
  'Off-Hand Drygore Mace',
  'Scripture of Ful',
  'Magma Tempest Ability Codex',
  'Croesus Foultorch',
  'Croesus Sporehammer',
  'Croesus Spore Sack',
  'Cryptbloom Helm (Incomplete)',
  'Cryptbloom Top (Incomplete)',
  'Cryptbloom Bottoms (Incomplete)',
  'Cryptbloom gloves (Incomplete)',
  'Cryptbloom boots (Incomplete)',
  'Scripture of Bik',
  'Fleeting boots',
  'Laceration boots',
  'Blast Diffusion boots',
  'Malevolent Kiteshield',
  'Merciless Kiteshield',
  'Vengeful Kiteshield',
  'Eldrich Crossbow Limb',
  'Eldrich Crossbow Stock',
  'Eldrich Crossbow Mechanism',
  'Frozen Core of Leng',
  'Orb of Volcanic Anima',
  'Orb of Corrupted Anima',
  'Orb of Pure Anima',
  'Fractured Armadyl Symbol',
  "Staff of Armadyl's Fractured Shaft",
  'Codex of Lost Knowledge',
  'Shadow Spike',
  'Greater Richochet Ability Codex',
  'Greater Chain Ability Codex',
  'Divert Ability Codex',
  'Obsidian Blade',
  'Magma Core',
  'Ancient Hilt',
  "Erethdor's Grimoire",
  'Praesul Codex',
  'Chaos Roar Ability Codex',
  'Vestments of Havoc Hood',
  'Vestments of Havoc Robe Top',
  'Vestments of Havoc Robe Bottom',
  'Vestments of Havoc boots',
  'Seismic Wand',
  'Seismic Singularity',
  'Blightbound Crossbow',
  'Off-Hand Blightbound Crossbow',
  'Purple Mushroom',
  "Merethiel's Stave",
  'Wand of the Praesul',
  'Imperium Core',
  'Dormant Seren Godbow',
  'Dormant Staff of Sliske',
  'Dormant Zaros Godsword',
  'Reprisal Ability Codex',
  'Intricate Smoke-Shrouded Chest',
  'Intricate Shadow Chest',
  'Intricate Blood Stained Chest',
  'Intricate Ice Chest',
  "Top of the Last Guardian's bow",
  'Divine bowstring',
  "Bottom of the Last Guardian's bow",
];

export function sanitizeString(input: string): string {
  return input
    .toLowerCase()
    .replace(/[!"#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~]/g, '')
    .replace(/\s+/g, '_');
}

export const NormalizedDropsToDrops: Record<string, string> = Object.fromEntries(
  Drops.map((drop) => [sanitizeString(drop), drop]),
);
